/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quotes;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {


    @Test
    public void test(){
        Gson gsonq = new Gson();
        String dataFile1 = App.readgson("C:\\Users\\Lenovo\\Desktop\\JAVA401\\classcode\\quotes\\app\\src\\test\\resources\\recentquotes8.json");
        qouteAuthor [] quotAoutherObj = gsonq.fromJson(dataFile1, qouteAuthor[].class);
        String testquot = String.valueOf(quotAoutherObj[0]);
        String test = "{author='Marilyn Monroe', text='I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.}";

        assertEquals(test, testquot);
    }

}