/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quotes;

import com.google.gson.Gson;

import java.io.FileReader;
import java.io.IOException;
import java.util.Objects;
import java.util.Random;


public class App {

    public static void main(String[] args) throws IOException {
        //URL apiLink =new URL("https://codefellows.github.io/code-401-java-guide/curriculum/class-08/recentquotes.json");
        FileReader gsonDataFile = readgson("recentquotes.json");
        qouteAuthor[] authorsAndQouts = qouteGson(gsonDataFile);
        for (int i = 0; i < authorsAndQouts.length; i++) {
            if (authorsAndQouts[i].getTest()==null) {
                continue;
            }
            System.out.println(authorsAndQouts[i].getTest());
        }
    }
////////////////////////////////////////////////////////////////////////////////////////////////

    // it return the index of element from the array or qouts
    public static int randomQoute(int lengthOfQout){
        Random random =new Random();
        int randomQoutNumber=random.nextInt(lengthOfQout);
        return randomQoutNumber;
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////

    //this to read the data from file using filereader
    public static FileReader readgson (String gsonFile){
        FileReader gsonFileReader=null ;
        try{
            String gsonData = Objects.requireNonNull(Thread.currentThread()
                    .getContextClassLoader().getResource(gsonFile)).getFile();
            gsonFileReader=new FileReader(gsonData);
        }catch (IOException exception){
            exception.printStackTrace();
        }
        return gsonFileReader;
    }
    ///////////////////////////////////////////////////////////////////////////////////////////////
    public static qouteAuthor[] qouteGson(FileReader  gsonD){
        Gson gson =new Gson ();
        qouteAuthor[] arrayOfQouteAuthor =gson.fromJson (gsonD, qouteAuthor[].class);
        return arrayOfQouteAuthor;
    }
}
