/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;


public class App {

    public static void main(String[] args) throws IOException {
////////////////////////////////////////////////////////////////////////////////////////////////
//                       LAB 08
////////////////////////////////////////////////////////////////////////////////////////////////

//        String gsonDataFile = readgson();
//
//        qouteAuthor[] authorsAndQouts = qouteGson(gsonDataFile);
//
//        System.out.println(authorsAndQouts[0]);
//        int randomElement =randomQoute(authorsAndQouts.length);
//        System.out.println(authorsAndQouts[randomElement] );
//
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////STECH  GOALS  FOR LAB 8/////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        // if the lingth of args =2  i mean hear the user add auther and qute (args[0] , args[1] )
//        if(args.length == 0){
//        int randomElement =randomQoute(authorsAndQouts.length);
//        }if (args.length==2){
//            if(args[0].equals("author")){
//            for (int i = 0; i < authorsAndQouts.length; i++) {
//                if(authorsAndQouts[i].getAuthor().contains(args[1])){
//                 continue;
//                }   System.out.println(authorsAndQouts[i].getText());
//                System.out.println(authorsAndQouts[i].toString());
//            }
//            }else if (args[0].equals("contains")){ // return a quote that contains that word
//                Boolean flag = false;
//                for (int i = 0; i < authorsAndQouts.length; i++) {
//                    if(authorsAndQouts[i].getText().contains(args[1])){
//                        continue;
//                    }
//                        System.out.println(authorsAndQouts[i].getText());
//
//        }
//        }
//    }

////////////////////////////////////////////////////////////////////////////////////////////////
//                       LAB 09
////////////////////////////////////////////////////////////////////////////////////////////////

        String gsonDataFile = readgson();

        ArrayList authorsAndQouts = qouteGson(gsonDataFile);
        System.out.println(authorsAndQouts);
            Gson gson = new Gson();
    try {
        URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");

        HttpURLConnection qoutUrl = (HttpURLConnection) url.openConnection();

        qoutUrl.setRequestMethod("GET");

        InputStreamReader dataStram = new InputStreamReader(qoutUrl.getInputStream());
        BufferedReader bufferedReader = new BufferedReader(dataStram);
        String qouteData = bufferedReader.readLine();

        QuotesAPI quotDataObj = gson.fromJson(qouteData, QuotesAPI.class);
        qouteAuthor quotApiCopy = new qouteAuthor(quotDataObj.getQuoteAuthor(),quotDataObj.getQuoteText());

        String gsonStr =gson.toJson(quotApiCopy);
        authorsAndQouts.add(gsonStr);

    }catch (IOException e){
        System.out.println(authorsAndQouts.get(randomQoute(authorsAndQouts.size())));
        System.out.println(e.getMessage());
    }
            File qoutandAoutherFile = new File("C:\\Users\\Lenovo\\Desktop\\JAVA401\\classcode\\quotes\\app\\src\\main\\resources\\recentquotes.json");
        try (FileWriter qoutandAouthertheFile = new FileWriter(qoutandAoutherFile)) {
            gson.toJson(authorsAndQouts, qoutandAouthertheFile);
        }catch (IOException e){
            System.out.println(e.getMessage());
        }

    }

////////////////////////////////////////////////////////////////////////////////////////////////

    public static int randomQoute(int lengthOfQout){
        Random random =new Random();
        int randomQoutNumber=random.nextInt(lengthOfQout);
        return randomQoutNumber;
    }

//////////////////////////////////////////////////////////////////////////////////////////////////////

    public static String readgson() {
        String sumLins = "";
        String newLine = "";
        BufferedReader reader = null;

        try {
            reader = new BufferedReader(new FileReader("C:\\Users\\Lenovo\\Desktop\\JAVA401\\classcode\\quotes\\app\\src\\main\\resources\\recentquotes.json"));
            newLine = reader.readLine();
            System.out.println(newLine);

            while (newLine != null) {
                sumLins += newLine + "\n";
                newLine = reader.readLine();
            }


        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        return sumLins;
    }
    ///////////////////////////////////////////////////////////////////////////////////////////////
    public static ArrayList qouteGson(String  gsonD){
        Gson gson =new Gson ();
        ArrayList qoutandAoutherstr = gson.fromJson(gsonD, ArrayList.class);
        return qoutandAoutherstr;
    }
}

